"""add renewal_obligations table

Revision ID: 31c5907ffcd8
Revises: c71eb2d4fa6f
Create Date: 2026-08-16 02:08:33.612537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c5907ffcd8'
down_revision: Union[str, Sequence[str], None] = 'c71eb2d4fa6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renewal_obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('source_text_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewal_obligations_contract_id'), 'renewal_obligations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_renewal_obligations_due_date'), 'renewal_obligations', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renewal_obligations_due_date'), table_name='renewal_obligations')
    op.drop_index(op.f('ix_renewal_obligations_contract_id'), table_name='renewal_obligations')
    op.drop_table('renewal_obligations')
    # ### end Alembic commands ###
