"""add email_sent to notifications

Revision ID: c5f57fbc0caf
Revises: 00f9b51dd45a
Create Date: 2026-08-16 15:04:10.248610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f57fbc0caf'
down_revision: Union[str, Sequence[str], None] = '00f9b51dd45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('email_sent', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'email_sent')
    # ### end Alembic commands ###
