"""add contract_templates table and contract source/nullable file_path

Revision ID: c71eb2d4fa6f
Revises: c5f52b8658ff
Create Date: 2026-08-16 01:09:06.740392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c71eb2d4fa6f'
down_revision: Union[str, Sequence[str], None] = 'c5f52b8658ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clause_outline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_instructions', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contracts', sa.Column('source', sa.String(length=20), nullable=False, server_default='uploaded'))
    op.alter_column('contracts', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('contracts', 'source')
    op.drop_table('contract_templates')
    # ### end Alembic commands ###
