"""add contract_summaries table

Revision ID: d1c2df880568
Revises: 21c78eb16970
Create Date: 2026-08-09 23:45:40.446822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1c2df880568'
down_revision: Union[str, Sequence[str], None] = '21c78eb16970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('key_obligations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('important_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks_flagged', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_text_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_summaries')
    # ### end Alembic commands ###
